// This file was automatically generated by TanStack Router. Do not edit it.
import { Route as IndexRoute } from "./routes/index";
import { Route as AboutRoute } from "./routes/about";

export const routeTree = [IndexRoute, AboutRoute];
